---
apiVersion: v1
kind: Service
metadata:
  name: palworld-svc
  namespace: gaming
  annotations:
    svc.k3s.io/loadbalancer-target: opti74
spec:
  type: LoadBalancer
  ports:
    - name: game
      port: 8211
      targetPort: 8211
      protocol: UDP
    - name: rcon
      port: 25575
      targetPort: 25575
      protocol: TCP
    - name: rest-api
      port: 8212
      targetPort: 8212
      protocol: TCP
  selector:
    app: palworld
