---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-pvc
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 25Gi
