---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: opnsense-firewall
  namespace: vms
  labels:
    app: opnsense
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/vm: opnsense-firewall
        app: opnsense
    spec:
      nodeSelector:
        kubernetes.io/hostname: workstation
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 1800
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 1800
      terminationGracePeriodSeconds: 60
      domain:
        machine:
          type: q35
        cpu:
          sockets: 1
          cores: 2
          threads: 1
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
          limits:
            cpu: "2"
            memory: 4Gi
        devices:
          inputs:
            - type: tablet
              bus: usb
              name: tablet
          disks:
            - name: boot-disk
              disk:
                bus: virtio
              bootOrder: 1
          interfaces:
            - name: default
              model: virtio
              masquerade: {}
            - name: lab-lan
              model: virtio
              binding:
                name: managedtap
          rng: {}
      networks:
        - name: default
          pod: {}
        - name: lab-lan
          multus:
            networkName: ovn-ad-vpc
      volumes:
        - name: boot-disk
          persistentVolumeClaim:
            claimName: opnsense-boot-pvc
