---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dc01
  namespace: vms
  labels:
    app: active-directory
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: dc01
        app: active-directory
    spec:
      nodeSelector:
        kubernetes.io/hostname: workstation
      terminationGracePeriodSeconds: 60
      domain:
        machine:
          type: q35
        cpu:
          sockets: 1
          cores: 4
          threads: 1
          model: host-passthrough
        resources:
          requests:
            cpu: "2"
            memory: 8Gi
          limits:
            cpu: "4"
            memory: 8Gi
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer: {}
            reset: {}
            runtime: {}
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        devices:
          blockMultiQueue: true
          inputs:
            - type: tablet
              bus: usb
              name: tablet
          disks:
            - name: boot-disk
              disk:
                bus: virtio
              bootOrder: 2
            - name: win-iso
              cdrom:
                bus: sata
              bootOrder: 1
            - name: virtio-drivers
              cdrom:
                bus: sata
          interfaces:
            - name: lab-lan
              bridge: {}
          rng: {}
      networks:
        - name: lab-lan
          multus:
            networkName: lab-lan-bridge
      volumes:
        - name: boot-disk
          persistentVolumeClaim:
            claimName: dc01-boot-pvc
        - name: win-iso
          persistentVolumeClaim:
            claimName: nas-isos-win2025-pvc
        - name: virtio-drivers
          persistentVolumeClaim:
            claimName: nas-isos-virtio-pvc
