---
# ==============================================================================
# ISO INSTALLER (NFS - TerraMaster Volume3)
# ==============================================================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-isos-sophos-pv
spec:
  claimRef:
    namespace: vms
    name: nas-isos-sophos-pvc
  capacity:
    storage: 10G
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.60
    path: /Volume3/isos/sophos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-isos-sophos-pvc
  namespace: vms
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: nas-isos-sophos-pv
  resources:
    requests:
      storage: 10G
  storageClassName: ""
---
# ==============================================================================
# DISK 1: OS / BOOT (M.2 NVMe Pool)
# ==============================================================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sophos-boot-pv
spec:
  claimRef:
    namespace: vms
    name: sophos-boot-pvc
  capacity:
    storage: 50G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 10.0.0.60:3260
    iqn: iqn.2026-09.us.lambertlab:sophos-boot
    lun: 0
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sophos-boot-pvc
  namespace: vms
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: sophos-boot-pv
  resources:
    requests:
      storage: 50G
  storageClassName: ""
---
# ==============================================================================
# DISK 2: REPORTS & LOGS (SATA Pool)
# ==============================================================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sophos-logs-pv
spec:
  claimRef:
    namespace: vms
    name: sophos-logs-pvc
  capacity:
    storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 10.0.0.60:3260
    iqn: iqn.2026-09.us.lambertlab:sophos-logs
    lun: 0
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sophos-logs-pvc
  namespace: vms
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: sophos-logs-pv
  resources:
    requests:
      storage: 100G
  storageClassName: ""
