apiVersion: v1
kind: Service
metadata:
  name: cockpit
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: default-insecure-transport@kubernetescrd
spec:
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: cockpit
  namespace: default
  labels:
    kubernetes.io/service-name: cockpit
addressType: IPv4
ports:
  - port: 9090
endpoints:
  - addresses:
      - "100.106.96.18"
