---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: vms/ovn-ad-vpc
