---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ad.server: |
    ad.lambertlab.us:53 {
        errors
        cache 30
        forward . 10.10.0.10 {
            max_fails 2
            health_check 5s
        }
    }
