---
replicaCount: 1

# We map our existing secret to the proxy config
config:
  existingSecret: oauth2-proxy-auth

# The official chart passes everything else natively through extraArgs
extraArgs:
  provider: "oidc"
  oidc-issuer-url: "https://login.microsoftonline.com/c8e5d5f1-237a-45a1-a913-5908b6042e39/v2.0"
  redirect-url: "https://auth.lambertlab.us/oauth2/callback"
  email-domain: "*"
  cookie-secure: "true"
  cookie-domain: ".lambertlab.us"
  whitelist-domain: ".lambertlab.us"
  reverse-proxy: "true"
  oidc-groups-claim: "groups"
  scope: "openid profile email"
  skip-provider-button: "true"
  upstream: "static://202"

ingress:
  enabled: true
  className: traefik
  path: /oauth2
  pathType: Prefix
  hosts:
    - auth.lambertlab.us
