apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ntfy
  labels:
    app: ntfy
spec:
  serviceName: ntfy
  replicas: 1
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:latest
          args: ["serve"]
          env:
            - name: TZ
              value: "America/New_York"
            - name: NTFY_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ntfy-secrets
                  key: base-url
            - name: NTFY_UPSTREAM_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ntfy-secrets
                  key: upstream-base-url
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: cache
              mountPath: "/var/cache/ntfy"
  volumeClaimTemplates:
    - metadata:
        name: cache
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
spec:
  type: NodePort
  selector:
    app: ntfy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080
