apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secrets
type: Opaque
stringData:
  base-url: "https://ntfy.lambertlab.us"
  upstream-base-url: "https://ntfy.sh"
---
apiVersion: v1
kind: Secret
metadata:
  name: homarr-secrets
type: Opaque
stringData:
  encryption-key: "your-secret-key-here" # User should update this
