apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: default
data:
  vault.hcl: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = true
    }

    storage "raft" {
      path    = "/vault/data"
      node_id = "vault-node-1"
    }

    cluster_addr = "http://vault.default.svc.cluster.local:8201"
