apiVersion: v1
kind: Pod
metadata:
  name: vault-migration
  namespace: default
spec:
  containers:
    - name: helper
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: data
          mountPath: /vault/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-vault-0
