---
apiVersion: v1
kind: Service
metadata:
  name: fg-firewall-mgmt
  namespace: vms
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: vms-fg-insecure-transport@kubernetescrd
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "fg_stickiness"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
spec:
  type: ClusterIP
  selector:
    kubevirt.io/vm: fg-firewall
  ports:
    - name: https-mgmt
      port: 443
      targetPort: 443
    - name: ssh-mgmt
      port: 22
      targetPort: 22
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: fg-insecure-transport
  namespace: vms
spec:
  insecureSkipVerify: true
  disableHTTP2: true
  maxIdleConnsPerHost: 10
  forwardingTimeouts:
    responseHeaderTimeout: 60s
    idleConnTimeout: 90s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fg-firewall-ingress
  namespace: vms
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd,default-admin-only-access@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: fortigate.lambertlab.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fg-firewall-mgmt
                port:
                  number: 443
