---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fg-firewall
  namespace: vms
  labels:
    app: fortigate
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: fg-firewall
        app: fortigate
    spec:
      terminationGracePeriodSeconds: 60
      domain:
        machine:
          type: q35
        cpu:
          sockets: 1
          cores: 1
          threads: 1
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "1"
            memory: 2Gi
        devices:
          disks:
            - name: boot-disk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: lab-lan
              bridge: {}
          rng: {}
      networks:
        - name: default
          pod: {}
        - name: lab-lan
          multus:
            networkName: lab-lan-bridge
      volumes:
        - name: boot-disk
          persistentVolumeClaim:
            claimName: fortigate-boot-pvc
