---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: lab-lan-bridge
spec:
  nodeSelector:
    kubernetes.io/os: linux
  desiredState:
    interfaces:
      - name: vxlan-lab
        type: vxlan
        state: up
        vxlan:
          id: 100
          remote: 239.1.1.1
          destination-port: 4789
      - name: br-lab0
        type: linux-bridge
        state: up
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: vxlan-lab
        ipv4:
          enabled: false
        ipv6:
          enabled: false
