---
name: Homelab CI
"on":
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: self-hosted
    steps:
      - name: Pre-cleanup Workspace
        run: |
          sudo rm -f /tmp/gitleaks.tmp
          sudo rm -rf ${{ github.workspace }}/../_temp/*

      - name: Checkout
        uses: actions/checkout@v6
        with:
          clean: true
          fetch-depth: 0

      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Write config files
        run: |
          echo "${{ secrets.ANSIBLE_CFG }}" > ansible/ansible.cfg
          echo "${{ secrets.INVENTORY }}" > ansible/homelab-nodes

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Ansible collections
        run: ansible-galaxy collection install community.crypto

      - name: Ansible Lint
        run: ansible-lint

      - name: YAML Lint
        run: yamllint .

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: TFLint
        run: tflint --recursive

      - name: Terraform Init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          TF_VAR_vault_ip: ${{ vars.VAULT_IP }}
          TF_VAR_vault_password: ${{ secrets.VAULT_TOKEN }}
          TF_VAR_vault_unseal_keys: ${{ secrets.VAULT_UNSEAL_KEYS }}
