---
name: Homelab CI
"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Write config files
        run: |
          echo "${{ secrets.ANSIBLE_CFG }}" > ansible/ansible.cfg
          echo "${{ secrets.INVENTORY }}" > ansible/homelab-nodes

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Ansible collections
        run: ansible-galaxy collection install community.crypto

      - name: Ansible Lint
        run: ansible-lint

      - name: YAML Lint
        run: yamllint .

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: TFLint
        run: tflint --recursive
