---
agent:
  image:
    tag: "9.3.2"
  fleet:
    enabled: true
    url: "https://100.106.96.18:8220"
    insecure: true
    preset: perNode
    tokenFromSecret:
      name: elastic-agent-token
      key: token
  presets:
    perNode:
      resources:
        limits:
          memory: 2000Mi
        requests:
          cpu: 100m
          memory: 400Mi

system:
  enabled: true
